"""add usage_period_start to users

Revision ID: 437e300f5baa
Revises: c3e9a1f5d802
Create Date: 2026-07-03 03:52:04.167979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437e300f5baa'
down_revision: Union[str, Sequence[str], None] = 'c3e9a1f5d802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usage_period_start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usage_period_start')
    # ### end Alembic commands ###
