"""add filing_alert_state table

Revision ID: 917997e6de48
Revises: 437e300f5baa
Create Date: 2026-07-03 04:33:38.732941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917997e6de48'
down_revision: Union[str, Sequence[str], None] = '437e300f5baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_alert_state',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_seen_accession_number', sa.String(length=32), nullable=True),
    sa.Column('last_seen_form', sa.String(length=20), nullable=True),
    sa.Column('last_seen_filing_date', sa.Date(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filing_alert_state')
    # ### end Alembic commands ###
