"""create symbols table

Revision ID: 9a4f8ab8c4c6
Revises: 0de6753e5c58
Create Date: 2026-07-03 20:07:39.100395

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4f8ab8c4c6'
down_revision: Union[str, Sequence[str], None] = '0de6753e5c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Die bisherigen 23 kuratierten Symbole (frueher agent/AgentAction.py
# COMPANY_SECTORS) als Seed, damit die Suche (api/routes/analyze.py
# search_symbols) und deren Popular-Fallback auch vor dem ersten Lauf von
# scripts/import_symbols.py funktionieren. sector/industry bleiben bewusst
# leer - werden lazy zur Analysezeit (DataLoader.get_company_profile) oder
# per --enrich-Lauf befuellt.
LEGACY_SYMBOLS = [
    ("AAPL", "Apple Inc.", "NASDAQ"),
    ("MO", "Altria Group Inc.", "NYSE"),
    ("GOOGL", "Alphabet Inc.", "NASDAQ"),
    ("TSLA", "Tesla Inc.", "NASDAQ"),
    ("AMD", "Advanced Micro Devices Inc.", "NASDAQ"),
    ("PYPL", "PayPal Holdings Inc.", "NASDAQ"),
    ("NVDA", "NVIDIA Corporation", "NASDAQ"),
    ("NKE", "Nike Inc.", "NYSE"),
    ("UNH", "UnitedHealth Group Incorporated", "NYSE"),
    ("XPEV", "XPeng Inc.", "NYSE"),
    ("OCGN", "Ocugen Inc.", "NASDAQ"),
    ("UAA", "Under Armour Inc.", "NYSE"),
    ("BABA", "Alibaba Group Holding Limited", "NYSE"),
    ("LUMN", "Lumen Technologies Inc.", "NYSE"),
    ("TTWO", "Take-Two Interactive Software Inc.", "NASDAQ"),
    ("BIDU", "Baidu Inc.", "NASDAQ"),
    ("JD", "JD.com Inc.", "NASDAQ"),
    ("CRSP", "CRISPR Therapeutics AG", "NASDAQ"),
    ("NVO", "Novo Nordisk A/S", "NYSE"),
    ("NFLX", "Netflix Inc.", "NASDAQ"),
    ("BYD", "BYD Company Limited", "OTC"),
    ("SAP", "SAP SE", "NYSE"),
    ("ILMN", "Illumina Inc.", "NASDAQ"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    # ### end Alembic commands ###

    symbols_table = sa.table(
        'symbols',
        sa.column('symbol', sa.String),
        sa.column('name', sa.String),
        sa.column('exchange', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('updated_at', sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(
        symbols_table,
        [
            {"symbol": symbol, "name": name, "exchange": exchange, "is_active": True, "updated_at": now}
            for symbol, name, exchange in LEGACY_SYMBOLS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
